mappings:
  properties:
    title:
      type: text
      analyzer: my_english
      copy_to: title_sort
    title_sort:
      type: keyword

    url:
      type: keyword

    tag:
      type: keyword

    indexed_at:
      type: date

    content:
      type: text
      analyzer: my_english

settings:
  analysis:
    filter:
      english_stop:
        type: stop
        stopwords: _english_
      english_stemmer:
        type: stemmer
        language: english
      english_possessive_stemmer:
        type: stemmer
        language: possessive_english
    analyzer:
      my_english:
        tokenizer: standard
        filter:
          - english_possessive_stemmer
          - lowercase
          - english_stop
          - english_stemmer
