mappings:
  properties:
    title:
      type: text
      analyzer: my_english

    title_sort:
      type: keyword

    url:
      type: keyword

    tag:
      type: keyword

    indexed_at:
      type: date

    content:
      type: text
      analyzer: my_english

settings:
  analysis:
    filter:
      english_stop:
        type: stop
        stopwords: _english_
      custom_stems:
        type: stemmer_override
        rules:
          # not "anim"
          - "anime => anime"
          - "animation => animation"
          - "animism => animism"
          - "animal, animals => animal"
      english_stemmer:
        type: stemmer
        language: english
      english_possessive_stemmer:
        type: stemmer
        language: possessive_english
    analyzer:
      my_english:
        tokenizer: standard
        filter:
          - english_possessive_stemmer
          - lowercase
          - english_stop
          - custom_stems
          - english_stemmer
